// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR7T_XSWrQC0TpEPLL3cWS_zPbDtbCaxs',
    appId: '1:405016981693:web:3206d1e1dfdc19d07947d4',
    messagingSenderId: '405016981693',
    projectId: 'easy-notes-5cee5',
    authDomain: 'easy-notes-5cee5.firebaseapp.com',
    storageBucket: 'easy-notes-5cee5.firebasestorage.app',
    measurementId: 'G-4KW96CBKEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnHHH5jcrVW2GMfbZ_kjgOM6FnBBSmJsw',
    appId: '1:405016981693:android:4b777f5cf301f6a57947d4',
    messagingSenderId: '405016981693',
    projectId: 'easy-notes-5cee5',
    storageBucket: 'easy-notes-5cee5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIyKPwXy_Sr6_AwmQTAUQPg-7WUkMySyk',
    appId: '1:405016981693:ios:85c1194b7910b80f7947d4',
    messagingSenderId: '405016981693',
    projectId: 'easy-notes-5cee5',
    storageBucket: 'easy-notes-5cee5.firebasestorage.app',
    iosBundleId: 'com.aquitan.easyNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIyKPwXy_Sr6_AwmQTAUQPg-7WUkMySyk',
    appId: '1:405016981693:ios:85c1194b7910b80f7947d4',
    messagingSenderId: '405016981693',
    projectId: 'easy-notes-5cee5',
    storageBucket: 'easy-notes-5cee5.firebasestorage.app',
    iosBundleId: 'com.aquitan.easyNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR7T_XSWrQC0TpEPLL3cWS_zPbDtbCaxs',
    appId: '1:405016981693:web:7e553b330aaf56247947d4',
    messagingSenderId: '405016981693',
    projectId: 'easy-notes-5cee5',
    authDomain: 'easy-notes-5cee5.firebaseapp.com',
    storageBucket: 'easy-notes-5cee5.firebasestorage.app',
    measurementId: 'G-4P7B34WWD2',
  );
}
